import { ResearchResult, ResearchRoom } from './research-agent'

export interface GoldenSpec {
  id: string
  keywords: string[]
  spec: ResearchResult
}

function room(
  name: string, w: number, d: number, h: number,
  wc: string, fc: string, fm: string
): ResearchRoom {
  return { name, width: w, depth: d, height: h, wallColor: wc, floorColor: fc, floorMaterial: fm, furniture: [] }
}

export const GOLDEN_SPECS: GoldenSpec[] = [
  {
    id: 'peranakan_shophouse',
    keywords: ['peranakan', 'shophouse', 'singapore shophouse'],
    spec: {
      buildingType: 'peranakan_shophouse',
      floorCount: 4,
      floorHeight: 12,
      architecturalStyle: 'peranakan chinese colonial',
      hasGlassFront: false,
      hasColonnade: true,
      exteriorMaterial: 'smoothplastic',
      totalWidth: 36,
      totalDepth: 22,
      exteriorColor: 'Sand yellow',
      roofColor: 'Dark green',
      culturalNotes: 'Straits Chinese shophouse with five-foot-way colonnade, ornate plasterwork, louvred green shutters, flat parapet roof',
      confidence: 100,
      wallMaterial: 'limestone',
      roofMaterial: 'slate',
      groundMaterial: 'pavement',
      columnMaterial: 'concrete',
      floorBandMaterial: 'smoothplastic',
      accentColor: 'Bright blue',
      columnColor: 'White',
      shutterColor: 'Dark green',
      floorBandColor: 'White',
      roofType: 'flat',
      hasPagodaRoof: false,
      hasBalcony: false,
      rooms: [
        room('Ground Floor Shop', 20, 12, 12, 'Dark green', 'Medium stone grey', 'concrete'),
        room('Upper Living Hall', 16, 10, 12, 'Sand yellow', 'Brick yellow', 'wood'),
        room('Master Bedroom', 14, 10, 12, 'Sand yellow', 'Brick yellow', 'wood'),
        room('Second Bedroom', 10, 8, 12, 'Sand yellow', 'Brick yellow', 'wood'),
        room('Kitchen', 8, 8, 12, 'White', 'Medium stone grey', 'concrete'),
        room('Bathroom', 5, 5, 12, 'White', 'White', 'marble'),
      ],
    },
  },
  {
    id: 'victorian_terrace',
    keywords: ['victorian terrace', 'victorian house', 'victorian terraced'],
    spec: {
      buildingType: 'victorian_terrace',
      floorCount: 3,
      floorHeight: 11,
      architecturalStyle: 'victorian brick classical',
      hasGlassFront: false,
      hasColonnade: false,
      exteriorMaterial: 'brick',
      totalWidth: 36,
      totalDepth: 24,
      exteriorColor: 'Reddish brown',
      roofColor: 'Really black',
      culturalNotes: 'Victorian red-brick terraced house with bay window, slate roof, ornate cornice and sash windows',
      confidence: 100,
      wallMaterial: 'brick',
      roofMaterial: 'slate',
      groundMaterial: 'cobblestone',
      columnMaterial: 'brick',
      floorBandMaterial: 'smoothplastic',
      accentColor: 'Dark green',
      shutterColor: 'Dark green',
      floorBandColor: 'White',
      roofType: 'hip',
      hasBalcony: false,
      rooms: [
        room('Front Parlour', 14, 12, 11, 'Cashmere', 'Reddish brown', 'wood'),
        room('Study', 12, 10, 11, 'Cashmere', 'Reddish brown', 'wood'),
        room('Kitchen', 10, 10, 11, 'White', 'Medium stone grey', 'concrete'),
        room('Master Bedroom', 14, 12, 11, 'White', 'Reddish brown', 'wood'),
        room('Bedroom', 12, 10, 11, 'Light grey', 'Reddish brown', 'wood'),
        room('Bathroom', 6, 6, 11, 'White', 'White', 'marble'),
      ],
    },
  },
  {
    id: 'modern_hospital',
    keywords: ['hospital', 'clinic', 'medical centre', 'medical center'],
    spec: {
      buildingType: 'modern_hospital',
      floorCount: 4,
      floorHeight: 12,
      architecturalStyle: 'modern clinical healthcare',
      hasGlassFront: false,
      hasColonnade: false,
      exteriorMaterial: 'smoothplastic',
      totalWidth: 80,
      totalDepth: 60,
      exteriorColor: 'White',
      roofColor: 'Light grey',
      culturalNotes: 'Modern hospital with emergency department, operating theatres, inpatient wards and pharmacy',
      confidence: 100,
      wallMaterial: 'smoothplastic',
      roofMaterial: 'concrete',
      groundMaterial: 'concrete',
      columnMaterial: 'smoothplastic',
      floorBandMaterial: 'smoothplastic',
      accentColor: 'Bright blue',
      floorBandColor: 'Light grey',
      roofType: 'flat',
      hasBalcony: false,
      rooms: [
        room('Emergency Room', 24, 20, 12, 'White', 'Light stone grey', 'concrete'),
        room('Reception', 20, 16, 12, 'White', 'Light stone grey', 'concrete'),
        room('Ward A', 22, 18, 12, 'Institutional white', 'Light stone grey', 'concrete'),
        room('Operating Theatre', 18, 16, 12, 'White', 'White', 'concrete'),
        room('Pharmacy', 14, 12, 12, 'White', 'Light stone grey', 'concrete'),
        room('Staff Room', 12, 10, 12, 'Light grey', 'Medium stone grey', 'concrete'),
        room('Bathroom', 6, 6, 12, 'White', 'White', 'concrete'),
        room('Cafeteria', 18, 14, 12, 'White', 'Medium stone grey', 'concrete'),
      ],
    },
  },
  {
    id: 'neoclassical_parliament',
    keywords: ['parliament', 'capitol', 'government building', 'neoclassical parliament'],
    spec: {
      buildingType: 'neoclassical_parliament',
      floorCount: 3,
      floorHeight: 14,
      architecturalStyle: 'neoclassical government',
      hasGlassFront: false,
      hasColonnade: true,
      exteriorMaterial: 'smoothplastic',
      totalWidth: 80,
      totalDepth: 60,
      exteriorColor: 'Cashmere',
      roofColor: 'Dark grey',
      culturalNotes: 'Neoclassical parliament with grand portico colonnade, ceremonial chamber and ministerial offices',
      confidence: 100,
      wallMaterial: 'smoothplastic',
      roofMaterial: 'slate',
      groundMaterial: 'marble',
      columnMaterial: 'marble',
      floorBandMaterial: 'smoothplastic',
      accentColor: 'Bright yellow',
      columnColor: 'White',
      floorBandColor: 'White',
      roofType: 'flat',
      hasBalcony: false,
      rooms: [
        room('Chamber', 30, 24, 14, 'Cashmere', 'Light stone grey', 'marble'),
        room('Library', 20, 16, 14, 'Cashmere', 'Reddish brown', 'wood'),
        room('Committee Room', 18, 14, 14, 'Light stone grey', 'Medium stone grey', 'concrete'),
        room('Grand Lobby', 22, 16, 14, 'White', 'White', 'marble'),
        room('Press Gallery', 14, 12, 14, 'Light grey', 'Medium stone grey', 'concrete'),
        room('Minister Office', 16, 12, 14, 'Cashmere', 'Reddish brown', 'wood'),
        room('Security Room', 12, 10, 14, 'Light grey', 'Medium stone grey', 'concrete'),
      ],
    },
  },
  {
    id: 'islamic_mosque',
    keywords: ['mosque', 'islamic mosque', 'masjid'],
    spec: {
      buildingType: 'islamic_mosque',
      floorCount: 1,
      floorHeight: 16,
      architecturalStyle: 'islamic mosque',
      hasGlassFront: false,
      hasColonnade: true,
      exteriorMaterial: 'smoothplastic',
      totalWidth: 60,
      totalDepth: 50,
      exteriorColor: 'White',
      roofColor: 'Bright blue',
      culturalNotes: 'Islamic mosque with domed prayer hall, minaret, ablution area and courtyard colonnade',
      confidence: 100,
      wallMaterial: 'smoothplastic',
      roofMaterial: 'concrete',
      groundMaterial: 'marble',
      columnMaterial: 'marble',
      floorBandMaterial: 'smoothplastic',
      accentColor: 'Bright yellow',
      columnColor: 'White',
      floorBandColor: 'Sand yellow',
      roofType: 'flat',
      hasBalcony: false,
      rooms: [
        room('Prayer Hall', 40, 30, 16, 'White', 'White', 'marble'),
        room('Wudu Room', 14, 12, 16, 'White', 'Medium stone grey', 'concrete'),
        room('Library', 14, 10, 16, 'White', 'Reddish brown', 'wood'),
        room('Office', 12, 10, 16, 'Light grey', 'Medium stone grey', 'concrete'),
        room('Storage', 8, 8, 16, 'Light grey', 'Medium stone grey', 'concrete'),
        room('Imam Quarters', 12, 10, 16, 'White', 'Medium stone grey', 'concrete'),
      ],
    },
  },
  {
    id: 'gothic_church',
    keywords: ['gothic church', 'church', 'cathedral', 'chapel'],
    spec: {
      buildingType: 'gothic_church',
      floorCount: 2,
      floorHeight: 18,
      architecturalStyle: 'gothic ecclesiastical',
      hasGlassFront: false,
      hasColonnade: false,
      exteriorMaterial: 'brick',
      totalWidth: 40,
      totalDepth: 60,
      exteriorColor: 'Light stone grey',
      roofColor: 'Dark grey',
      culturalNotes: 'Gothic church with pointed arches, nave, chancel, bell tower and stained glass windows',
      confidence: 100,
      wallMaterial: 'limestone',
      roofMaterial: 'slate',
      groundMaterial: 'cobblestone',
      columnMaterial: 'limestone',
      floorBandMaterial: 'limestone',
      accentColor: 'Bright yellow',
      columnColor: 'Light stone grey',
      floorBandColor: 'White',
      roofType: 'gable',
      hasBalcony: false,
      rooms: [
        room('Nave', 28, 36, 18, 'Light stone grey', 'Reddish brown', 'wood'),
        room('Chancel', 18, 16, 18, 'Light stone grey', 'Medium stone grey', 'concrete'),
        room('Vestry', 10, 10, 18, 'Light grey', 'Medium stone grey', 'concrete'),
        room('Bell Tower', 8, 8, 18, 'Light stone grey', 'Medium stone grey', 'concrete'),
        room('Crypt', 20, 16, 18, 'Dark grey', 'Dark grey', 'concrete'),
        room('Parish Office', 10, 8, 18, 'Light grey', 'Reddish brown', 'wood'),
      ],
    },
  },
  {
    id: 'modern_apartment',
    keywords: ['apartment block', 'apartment building', 'residential block', 'flats'],
    spec: {
      buildingType: 'modern_apartment',
      floorCount: 6,
      floorHeight: 10,
      architecturalStyle: 'modern residential',
      hasGlassFront: false,
      hasColonnade: false,
      exteriorMaterial: 'smoothplastic',
      totalWidth: 50,
      totalDepth: 30,
      exteriorColor: 'Light grey',
      roofColor: 'Dark grey',
      culturalNotes: 'Modern apartment block with multiple residential units, communal lobby and laundry room',
      confidence: 100,
      wallMaterial: 'smoothplastic',
      roofMaterial: 'concrete',
      groundMaterial: 'concrete',
      columnMaterial: 'smoothplastic',
      floorBandMaterial: 'smoothplastic',
      accentColor: 'Bright blue',
      floorBandColor: 'White',
      roofType: 'flat',
      hasBalcony: true,
      rooms: [
        room('Lobby', 20, 14, 10, 'White', 'Light stone grey', 'concrete'),
        room('Unit A Living', 16, 12, 10, 'White', 'Reddish brown', 'wood'),
        room('Unit A Bedroom', 12, 10, 10, 'Light grey', 'Reddish brown', 'wood'),
        room('Unit B Living', 16, 12, 10, 'White', 'Reddish brown', 'wood'),
        room('Unit B Bedroom', 12, 10, 10, 'Light grey', 'Reddish brown', 'wood'),
        room('Laundry Room', 8, 6, 10, 'White', 'Medium stone grey', 'concrete'),
      ],
    },
  },
  {
    id: 'police_station',
    keywords: ['police station', 'police'],
    spec: {
      buildingType: 'police_station',
      floorCount: 2,
      floorHeight: 11,
      architecturalStyle: 'victorian government institutional',
      hasGlassFront: false,
      hasColonnade: false,
      exteriorMaterial: 'brick',
      totalWidth: 50,
      totalDepth: 36,
      exteriorColor: 'Medium stone grey',
      roofColor: 'Dark grey',
      culturalNotes: 'Victorian institutional police station with public counter, holding cells, CID offices and briefing room',
      confidence: 100,
      wallMaterial: 'brick',
      roofMaterial: 'slate',
      groundMaterial: 'concrete',
      columnMaterial: 'brick',
      floorBandMaterial: 'smoothplastic',
      accentColor: 'Dark green',
      floorBandColor: 'White',
      roofType: 'hip',
      hasBalcony: false,
      rooms: [
        room('Reception', 16, 12, 11, 'Light grey', 'Medium stone grey', 'concrete'),
        room('Holding Cell', 12, 10, 11, 'Dark grey', 'Dark grey', 'concrete'),
        room('Briefing Room', 14, 12, 11, 'Light grey', 'Medium stone grey', 'concrete'),
        room('Office', 14, 12, 11, 'Light grey', 'Medium stone grey', 'concrete'),
        room('Evidence Room', 10, 8, 11, 'Light grey', 'Medium stone grey', 'concrete'),
        room('Locker Room', 10, 8, 11, 'Light grey', 'Medium stone grey', 'concrete'),
      ],
    },
  },
  {
    id: 'fire_station',
    keywords: ['fire station', 'firehouse', 'fire brigade', 'fire department'],
    spec: {
      buildingType: 'fire_station',
      floorCount: 2,
      floorHeight: 12,
      architecturalStyle: 'modern fire station',
      hasGlassFront: false,
      hasColonnade: false,
      exteriorMaterial: 'smoothplastic',
      totalWidth: 60,
      totalDepth: 40,
      exteriorColor: 'Bright red',
      roofColor: 'Dark grey',
      culturalNotes: 'Modern fire station with large vehicle bays, crew dormitory, watch room and equipment store',
      confidence: 100,
      wallMaterial: 'smoothplastic',
      roofMaterial: 'concrete',
      groundMaterial: 'concrete',
      columnMaterial: 'smoothplastic',
      floorBandMaterial: 'smoothplastic',
      accentColor: 'Bright yellow',
      floorBandColor: 'White',
      roofType: 'flat',
      hasBalcony: false,
      rooms: [
        room('Vehicle Bay A', 22, 18, 12, 'Light grey', 'Dark grey', 'concrete'),
        room('Vehicle Bay B', 22, 18, 12, 'Light grey', 'Dark grey', 'concrete'),
        room('Crew Room', 16, 12, 12, 'Light grey', 'Medium stone grey', 'concrete'),
        room('Kitchen', 10, 10, 12, 'White', 'Medium stone grey', 'concrete'),
        room('Dormitory', 16, 12, 12, 'Light grey', 'Reddish brown', 'wood'),
        room('Watch Room', 10, 8, 12, 'Light grey', 'Medium stone grey', 'concrete'),
      ],
    },
  },
  {
    id: 'australian_brick_house',
    keywords: ['australian house', 'australian', 'aussie house', 'brick house', 'modern house australia', 'australian residential'],
    spec: {
      buildingType: 'australian_brick_house',
      floorCount: 2,
      floorHeight: 12,
      architecturalStyle: 'australian modern residential brick',
      hasGlassFront: false,
      hasColonnade: false,
      exteriorMaterial: 'brick',
      totalWidth: 52,
      totalDepth: 32,
      exteriorColor: 'Reddish brown',
      roofColor: 'Dark grey',
      culturalNotes: 'Australian modern brick veneer house with colorbond shed roof, double garage, balcony and dark-framed aluminium windows',
      confidence: 100,
      wallMaterial: 'brick',
      roofMaterial: 'metal',
      groundMaterial: 'concrete',
      columnMaterial: 'smoothplastic',
      floorBandMaterial: 'smoothplastic',
      accentColor: 'Really black',
      floorBandColor: 'Light stone grey',
      roofType: 'shed',
      hasBalcony: true,
      hasPagodaRoof: false,
      windowStyle: 'rectangular',
      rooms: [
        { ...room('Garage', 24, 16, 12, 'Medium stone grey', 'Medium stone grey', 'concrete'), floor: 0 },
        { ...room('Living Room', 20, 16, 12, 'White', 'Brick yellow', 'wood'), floor: 1 },
        { ...room('Master Bedroom', 16, 14, 12, 'White', 'Brick yellow', 'wood'), floor: 1 },
        { ...room('Bedroom 2', 14, 12, 12, 'White', 'Brick yellow', 'wood'), floor: 1 },
        { ...room('Kitchen', 16, 12, 12, 'White', 'Medium stone grey', 'concrete'), floor: 1 },
      ],
    },
  },
  {
    id: 'medieval_castle',
    keywords: ['castle', 'medieval castle', 'fortress', 'fortification'],
    spec: {
      buildingType: 'medieval_castle',
      floorCount: 4,
      floorHeight: 14,
      architecturalStyle: 'medieval castle fortress',
      hasGlassFront: false,
      hasColonnade: false,
      exteriorMaterial: 'brick',
      totalWidth: 80,
      totalDepth: 80,
      exteriorColor: 'Medium stone grey',
      roofColor: 'Dark grey',
      culturalNotes: 'Medieval castle with great hall, dungeon, armoury, chapel, kitchen and battlements',
      confidence: 100,
      wallMaterial: 'concrete',
      roofMaterial: 'slate',
      groundMaterial: 'cobblestone',
      columnMaterial: 'limestone',
      floorBandMaterial: 'limestone',
      accentColor: 'Really black',
      columnColor: 'Medium stone grey',
      floorBandColor: 'Dark grey',
      roofType: 'flat',
      hasBalcony: false,
      rooms: [
        room('Great Hall', 30, 24, 14, 'Medium stone grey', 'Reddish brown', 'wood'),
        room('Throne Room', 20, 16, 14, 'Dark grey', 'Medium stone grey', 'concrete'),
        room('Dungeon', 16, 12, 14, 'Dark stone grey', 'Dark grey', 'concrete'),
        room('Armoury', 14, 12, 14, 'Dark grey', 'Medium stone grey', 'concrete'),
        room('Chapel', 12, 10, 14, 'Light stone grey', 'Medium stone grey', 'concrete'),
        room('Kitchen', 14, 12, 14, 'Light grey', 'Medium stone grey', 'concrete'),
        room('Barracks', 16, 12, 14, 'Medium stone grey', 'Reddish brown', 'wood'),
        room('Guard Tower', 8, 8, 14, 'Medium stone grey', 'Medium stone grey', 'concrete'),
      ],
    },
  },
]

function kwMatch(search: string, kw: string): boolean {
  return kw.toLowerCase().split(/\s+/).every(w => search.includes(w))
}

export function findGoldenSpec(buildingType: string, prompt?: string): GoldenSpec | null {
  const search = ((buildingType || '') + ' ' + (prompt || ''))
    .toLowerCase()
    .replace(/_/g, ' ')

  // Explicit Australian house matching
  const isAussieHouse =
    (search.includes('australian') && (search.includes('house') || search.includes('residential') || search.includes('brick'))) ||
    (search.includes('aussie') && search.includes('house')) ||
    search.includes('brick house')
  if (isAussieHouse) {
    const spec = GOLDEN_SPECS.find(s => s.id === 'australian_brick_house')
    if (spec) return spec
  }

  let bestSpec: GoldenSpec | null = null
  let bestScore = 0
  for (const spec of GOLDEN_SPECS) {
    let score = 0
    for (const kw of spec.keywords) {
      if (kwMatch(search, kw)) score++
    }
    if (score > bestScore) {
      bestScore = score
      bestSpec = spec
    }
  }
  return bestScore > 0 ? bestSpec : null
}

export function goldenSpecToResearch(spec: GoldenSpec): ResearchResult {
  return { ...spec.spec, confidence: 100 }
}
