import { RbxPart } from './rbxmx'
import type { ResearchResult } from './research-agent'
import { buildOttomanHouse } from './modes/ottoman-house'

const MAT_LUA: Record<string, string> = {
  concrete: 'Concrete',
  woodplanks: 'WoodPlanks',
  glass: 'Glass',
  slate: 'Slate',
  pebble: 'Pebble',
  granite: 'Granite',
  smoothplastic: 'SmoothPlastic',
  brick: 'Brick',
  wood: 'Wood',
  metal: 'Metal',
  marble: 'Marble',
  fabric: 'Fabric',
  neon: 'Neon',
  sand: 'Sand',
  ice: 'Ice',
  cobblestone: 'Cobblestone',
  sandstone: 'Sandstone',
  corrodedmetal: 'CorrodedMetal',
}

function fmt(v: number): string {
  return parseFloat(v.toFixed(4)).toString()
}

function partToLua(part: RbxPart): string {
  const mat = MAT_LUA[(part.material || '').toLowerCase().trim()] ?? 'SmoothPlastic'
  const partType = part.partType ?? 'Part'
  const r00 = part.r00 ?? 1; const r01 = part.r01 ?? 0; const r02 = part.r02 ?? 0
  const r10 = part.r10 ?? 0; const r11 = part.r11 ?? 1; const r12 = part.r12 ?? 0
  const r20 = part.r20 ?? 0; const r21 = part.r21 ?? 0; const r22 = part.r22 ?? 1
  const transparency = part.transparency ?? 0

  const fields = [
    `name="${part.name}"`,
    `sx=${fmt(part.size.x)},sy=${fmt(part.size.y)},sz=${fmt(part.size.z)}`,
    `px=${fmt(part.position.x)},py=${fmt(part.position.y)},pz=${fmt(part.position.z)}`,
    `color="${part.color}"`,
    `material="${mat}"`,
    `transparency=${fmt(transparency)}`,
    `r00=${fmt(r00)},r01=${fmt(r01)},r02=${fmt(r02)}`,
    `r10=${fmt(r10)},r11=${fmt(r11)},r12=${fmt(r12)}`,
    `r20=${fmt(r20)},r21=${fmt(r21)},r22=${fmt(r22)}`,
  ]
  if (partType !== 'Part') fields.push(`partType="${partType}"`)

  return `makePart({${fields.join(',')}})`
}

// Names generated by buildOttomanHouse that we replace with the WedgePart hip roof
const OTTOMAN_REPLACED_NAMES = new Set([
  'RoofEave', 'RoofMid1', 'RoofMid2', 'RoofRidge',
  'FasciaF', 'FasciaB', 'FasciaL', 'FasciaR', 'StoneBase',
])

const OTTOMAN_EXTRA_PARTS: RbxPart[] = [
  {
    name: 'StoneBase', size: { x: 30.18, y: 5.94, z: 28.94 },
    position: { x: -0.266, y: 2.97, z: 0.394 },
    color: 'Fossil', material: 'granite', anchored: true, transparency: 0,
  },
  {
    name: 'RoofF', size: { x: 28, y: 2.5, z: 4 },
    position: { x: 0, y: 23.2, z: 13.5 },
    color: 'Dark red', material: 'pebble', anchored: true, transparency: 0,
    partType: 'WedgePart',
    r00: 1, r01: 0, r02: 0, r10: 0, r11: 1, r12: 0, r20: 0, r21: 0, r22: 1,
  },
  {
    name: 'RoofB', size: { x: 28, y: 2.5, z: 4 },
    position: { x: 0, y: 23.2, z: -13.5 },
    color: 'Dark red', material: 'pebble', anchored: true, transparency: 0,
    partType: 'WedgePart',
    r00: -1, r01: 0, r02: 0, r10: 0, r11: 1, r12: 0, r20: 0, r21: 0, r22: -1,
  },
  {
    name: 'RoofL', size: { x: 4, y: 2.5, z: 26 },
    position: { x: -14.5, y: 23.2, z: 0 },
    color: 'Dark red', material: 'pebble', anchored: true, transparency: 0,
    partType: 'WedgePart',
    r00: 0, r01: 0, r02: 1, r10: 0, r11: 1, r12: 0, r20: -1, r21: 0, r22: 0,
  },
  {
    name: 'RoofR', size: { x: 4, y: 2.5, z: 26 },
    position: { x: 14.5, y: 23.2, z: 0 },
    color: 'Dark red', material: 'pebble', anchored: true, transparency: 0,
    partType: 'WedgePart',
    r00: 0, r01: 0, r02: -1, r10: 0, r11: 1, r12: 0, r20: 1, r21: 0, r22: 0,
  },
  {
    name: 'RoofDeck', size: { x: 28, y: 0.5, z: 26 },
    position: { x: 0, y: 23.6, z: 0 },
    color: 'Dark red', material: 'pebble', anchored: true, transparency: 0,
  },
]

export function generateLuaScript(researchResult: ResearchResult, parts: RbxPart[]): string {
  let finalParts: RbxPart[]

  if (researchResult.buildingType === 'ottoman_house') {
    const ottomanParts = buildOttomanHouse(0)
    const wallParts = ottomanParts
      .filter(p => !OTTOMAN_REPLACED_NAMES.has(p.name))
    finalParts = [...wallParts, ...OTTOMAN_EXTRA_PARTS]
  } else {
    finalParts = parts
  }

  const header = `-- TurboBuilder: ${researchResult.buildingType} (${finalParts.length} parts)`
  return [header, ...finalParts.map(partToLua)].join('\n')
}
